before_script:
        - wget http://www.cmake.org/files/v3.14/cmake-3.14.5-Linux-x86_64.tar.gz && tar xzf cmake-3.14.5-Linux-x86_64.tar.gz

matrix:
  include:
    - language: cpp
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - libeigen3-dev
          - libboost1.58-all
          - libasound2-dev
          - python3-numpy
          - maven
      
      env: PYTHON_HOME=/usr
           PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH
           CXX=g++-7 
           PLATFORM=Linux

    - language: android
      dist: trusty
      addons:
        apt:
          packages:
          - maven
          - bzip2
      before_install:
      - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
      - unzip -q android-ndk-r18b-linux-x86_64.zip -d $HOME
      - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
      - export PATH=$PATH:$ANDROID_NDK_HOME
      - mkdir "$ANDROID_HOME/licenses" || true		
      - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"		
      - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"	
      - $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir $HOME/android-clang-toolchain
      - export CXX=$HOME/android-clang-toolchain/bin/arm-linux-androideabi-clang++
      - wget https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0_2/boost-android-r18b-armeabi-v7a-1.68.0.zip
      - mkdir "$HOME/boost" || true		
      - unzip -q boost-android-r18b-armeabi-v7a-1.68.0.zip -d $HOME/boost
      - export BOOST_ROOT=$HOME/boost
      - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2
      - tar jxf 3.3.4.tar.bz2 -C $HOME
      - export EIGEN_ROOT=$HOME/eigen-eigen-5a0156e40feb
      - export CMAKE_ARGS="-DBoost_NO_SYSTEM_PATHS=ON -DBOOST_INCLUDEDIR=$BOOST_ROOT/include/ -DBOOST_LIBRARYDIR=$BOOST_ROOT/lib/armeabi-v7a -DEigen3_INCLUDE_DIRS=$EIGEN_ROOT"
      - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      android:
        components:
          - tools
          - platform-tools
          - build-tools-26.0.2
          - android-22
          - android-26
          - sys-img-armeabi-v7a-android-22  
      env: PYTHON_HOME=/usr
           PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin:$PATH
           PLATFORM=Android

script:
        -  mkdir cmake-build && cd cmake-build && ../cmake-3.14.5-Linux-x86_64/bin/cmake -DPLATFORM=$PLATFORM $CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=../install ../ && make -j4 install && make test ARGS="-V"

